apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: monitoring
  labels:
    app: cloudflared
spec:
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cloudflared-metrics
  namespace: monitoring
  labels:
    app: cloudflared
subsets:
  - addresses:
      - ip: 192.168.18.178
    ports:
      - name: metrics
        port: 2000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
