apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "8.4.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    grafana.ini:
      date_formats:
        default_week_start: monday
      security:
        allow_embedding: true

    admin:
      existingSecret: grafana-admin-credentials
      passwordKey: admin-password

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - hosts:
            - grafana.jmartinn.net
          secretName: grafana-ingress-production
      hosts:
        - grafana.jmartinn.net
