apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  settings.yaml: |
    title: Your Homelab Dashboard
    theme: dark
    color: slate
    favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-192x192.png

  kubernetes.yaml: |
    mode: cluster
    discovery: false
    cluster:
      api: https://kubernetes.default.svc
      serviceAccount:
        tokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token

  services.yaml: |
    - name: System & Monitoring
      icon: chart-line
      items:
        - name: Grafana
          icon: chart-bar
          href: https://grafana.jmartinn.net
          description: System Monitoring & Metrics
          indicator: true

    - name: Gaming
      icon: gamepad
      items:
        - name: Minecraft Server
          icon: cube
          href: minecraft.jmartinn.net
          description: Minecraft Server
          indicator: true
          widget:
            type: button
            buttons:
            - icon: play
              text: Start
              action: kubectl scale deployment -n minecraft minecraft --replicas=1
            - icon: stop 
              text: Stop
              action: kubectl scale deployment -n minecraft minecraft --replicas=0
            - icon: refresh
              text: Restart
              action: kubectl rollout restart deployment -n minecraft minecraft
          
    - name: Infrastructure
      icon: server
      items:
        - name: Homepage
          icon: house
          href: https://homepage.jmartinn.net
          description: Homelab Dashboard
          indicator: true

    - name: Network
      icon: wifi
      items:
        - name: Cloudflare
          icon: cloud
          href: https://dash.cloudflare.com
          description: DNS & Tunnel Management
