apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: minecraft-mods
    files:
      - mods/
