apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  ports:
    - name: minecraft  # Add a name for the game port
      port: 25565
      targetPort: 25565
      protocol: TCP
    - name: metrics    # Ensure metrics port has a name
      port: 9225
      targetPort: 9225
  selector:
    app: minecraft
